### ISSUE TITLE
Error in fetch array and not showing submit button on add list

### ISSUE THREAD

**Issue by imdewan** [pepiuox/PHP-GrapesJS#2]
![Screenshot (1)](https://user-images.githubusercontent.com/65299428/90280598-cf1e2800-de88-11ea-8d66-8462c12b2172.png)
![Screenshot (2)](https://user-images.githubusercontent.com/65299428/90280604-d2191880-de88-11ea-81c8-e4f67e0c0776.png)

**Comment by pepiuox** [comment]
Thank you very much for your contribution, now you can verify, the error is corrected

**Comment by imdewan** [comment]
<img width="960" alt="123" src="https://user-images.githubusercontent.com/65299428/90316758-0bfa2580-df42-11ea-843e-a374aa6b03fa.png">
<img width="960" alt="121" src="https://user-images.githubusercontent.com/65299428/90316760-0dc3e900-df42-11ea-90d8-f19d3c811007.png">

the first error comes if we didn't upload error and the second one comes if we fill all inputs. Also the page doesn't create

**Comment by imdewan** [comment]
![image](https://user-images.githubusercontent.com/65299428/90316974-c2123f00-df43-11ea-8827-a80f09d5a704.png)

After adding a folder 'uploads' reduces some errors but the page is still not created

**Comment by pepiuox** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/65299428/90316974-c2123f00-df43-11ea-8827-a80f09d5a704.png)
> 
> After adding a folder 'uploads' reduces some errors but the page is still not created

add.php is updated now.

**Comment by imdewan** [comment]
![image](https://user-images.githubusercontent.com/65299428/90327732-5caa6680-dfb4-11ea-838a-30d91e00414e.png)

There is some sql error so i echo it.. have a look.

**Comment by imdewan** [comment]
Thank u for ur help but i solved the error
add this line in add.php after  $parent = $_POST['parent']; ---

if(!is_int($parent)){
	$parent = 0;
		}

**Comment by pepiuox** [comment]
> 
> 
> Thank u for ur help but i solved the error
> add this line in add.php after $parent = $_POST['parent']; ---
> 
> if(!is_int($parent)){
> $parent = 0;
> }
 In the **page table**, **parent** is default '0',  if not is selected you can use
// If parent not is integer or is empty
if (!is_int($parent) || empty($parent)) {
   $parent = 0;
 }

// Store in folder pages
$directory = 'pages/';
//Check if the directory already exists.
if (!is_dir($directory)) {
    //Directory does not exist, so lets create it.
    mkdir($directory, 0755, true);
}
// If you use and make php file
// $link_path = $directory . $link . ".php";
// If you use and make html file
$link_path = $directory . $link . ".html";
$myfile = fopen($link_path, "w") or die("Unable to open file!");
// For redirect php
// $txt = '<?php header("Location: ../view.php?id=' . $last_id . '"); ?>';
// For redirect html
$txt = '<html><head><script>window.location.replace("../view.php?id=' . $last_id . '");</script></head><body></body></html>';
fwrite($myfile, $text);
fclose($myfile);

**Comment by pepiuox** [comment]
Sorry this code is for php
// For redirect php
$txt = '<?php header("Location: ../view.php?id=' . $last_id . '"); ?>';
If not see the code check last update, I added your code
